packages:
  - packages/*

overrides:
  '@modelcontextprotocol/sdk': 1.30.0
  '@hono/node-server': 2.0.12

allowBuilds:
  '@applemusic-like-lyrics/core': false
  '@applemusic-like-lyrics/lyric': false
  '@applemusic-like-lyrics/react': false
  '@swc/core': false
  esbuild: true
  msw: false
